[pytest]
addopts = -p no:launch_testing -p no:launch_ros
pythonpath =
    ros2_ws/src/astro_base
    ros2_ws/src/astro_ai
    ros2_ws/src/astro_audio
    ros2_ws/src/astro_vision
testpaths =
    ros2_ws/src/astro_base/test
    ros2_ws/src/astro_ai/test
    ros2_ws/src/astro_audio/test
    ros2_ws/src/astro_vision/test

